---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Develop - JavaScript | Directories
  ansible.builtin.file:
    path: '{{ item | ansible.builtin.dirname }}'
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env['NODE_REPL_HISTORY'] }}"
    - "{{ ansible_env['NPM_CONFIG_USERCONFIG'] }}"
  loop_control:
    label: '{{ item | ansible.builtin.dirname }}'
- name: Develop - JavaScript | Config link
  ansible.builtin.file:
    src: '{{ dotfyls_role_files }}/npmrc'
    path: "{{ ansible_env['NPM_CONFIG_USERCONFIG'] }}"
    state: link
    mode: '0644'
