---@module "lazy"
---@type LazySpec
return {
    "nvim-treesitter/nvim-treesitter",
    build = function() require("nvim-treesitter.install").update({ with_sync = true })() end,
    dependencies = { "OXY2DEV/markview.nvim", optional = true }, -- Has to load first.
    main = "nvim-treesitter.configs",
    cmd = {
        "TSBufDisable",
        "TSBufEnable",
        "TSBufToggle",
        "TSConfigInfo",
        "TSDisable",
        "TSEditQuery",
        "TSEditQueryUserAfter",
        "TSEnable",
        "TSInstall",
        "TSInstallFromGrammar",
        "TSInstallInfo",
        "TSInstallSync",
        "TSModuleInfo",
        "TSToggle",
        "TSUninstall",
        "TSUpdate",
        "TSUpdateSync",
    },
    event = { "BufNewFile", "BufReadPost" },
    init = function(plugin)
        -- Plugins do not `require`, so make queries available.
        require("lazy.core.loader").add_to_rtp(plugin)
        require("nvim-treesitter.query_predicates")
    end,
    opts = {
        ensure_installed = {
            "astro",
            "bash",
            "blueprint",
            "c",
            "comment",
            "commonlisp",
            "cpp",
            "css",
            "csv",
            "diff",
            "fish",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "go",
            "gomod",
            "gosum",
            "gowork",
            "html",
            "hyprlang",
            "ini",
            "java",
            "javascript",
            "jsdoc",
            "json",
            "json5",
            "jsonc",
            "just",
            "kotlin",
            "lua",
            "luadoc",
            "luap",
            "luau",
            "make",
            "markdown",
            "markdown_inline",
            "meson",
            "nix",
            "passwd",
            "python",
            "query",
            "regex",
            "requirements",
            "rust",
            "scss",
            "slint",
            "sql",
            "ssh_config",
            "svelte",
            "toml",
            "tsx",
            "typescript",
            "typst",
            "udev",
            "vala",
            "vhs",
            "vim",
            "vimdoc",
            "vue",
            "xml",
            "xresources",
            "yaml",
            "zathurarc",
            "zig",
        },
        highlight = { enable = true },
        indent = { enable = true },
    },
}
