[package]
name = "member3"
version.workspace = true
authors.workspace = true
license-file.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
