---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Develop - Rust | Initialize rustup
  ansible.builtin.command:
    cmd: rustup-init -qy --no-modify-path
    creates: "{{ ansible_env['RUSTUP_HOME'] }}"
- name: Develop - Rust | Configure musl target (static libc)
  ansible.builtin.command: rustup target add x86_64-unknown-linux-musl
  register: result
  changed_when: "'installing' in result.stderr"
- name: Develop - Rust | Install utilities
  ansible.builtin.command: cargo install {{ item }} --locked
  register: result
  changed_when: "'already installed' not in result.stderr"
  loop:
    - cargo-expand
    - cargo-msrv
    - cargo-udeps
    - cargo-update
    - sqlx-cli
