---
- name: Essential | Install
  ansible.builtin.dnf:
    name: '{{ item }}'
  become: true
  loop:
    - coreutils
    - findutils
    - gawk
    - git
    - grep
    - man-db
    - perl-interpreter
    - sed
    - wget
