---
- name: Distrobox | Install dependencies
  ansible.builtin.dnf:
    name: '{{ item }}'
  become: true
  loop:
    - podman
  # 1.7.0 makes exporting binaries much cleaner
- name: Distrobox | Download
  ansible.builtin.git:
    repo: https://github.com/89luca89/distrobox.git
    dest: '{{ dotfyls_role_files }}'
    version: release
    single_branch: true
  register: git_result
- name: Distrobox | Check install
  ansible.builtin.stat:
    path: "{{ ansible_env['HOME'] }}/.local/{{ item }}"
  register: stat_result
  when: git_result.after == git_result.before
  failed_when: not stat_result.stat.exists
  ignore_errors: true
  loop:
    - "bin/distrobox"
    - "bin/distrobox-assemble"
    - "bin/distrobox-create"
    - "bin/distrobox-enter"
    - "bin/distrobox-ephemeral"
    - "bin/distrobox-export"
    - "bin/distrobox-generate-entry"
    - "bin/distrobox-host-exec"
    - "bin/distrobox-init"
    - "bin/distrobox-list"
    - "bin/distrobox-rm"
    - "bin/distrobox-stop"
    - "bin/distrobox-upgrade"
    - "share/man/man1/distrobox.1"
    - "share/man/man1/distrobox-assemble.1"
    - "share/man/man1/distrobox-compatibility.1"
    - "share/man/man1/distrobox-create.1"
    - "share/man/man1/distrobox-enter.1"
    - "share/man/man1/distrobox-ephemeral.1"
    - "share/man/man1/distrobox-export.1"
    - "share/man/man1/distrobox-generate-entry.1"
    - "share/man/man1/distrobox-host-exec.1"
    - "share/man/man1/distrobox-init.1"
    - "share/man/man1/distrobox-list.1"
    - "share/man/man1/distrobox-rm.1"
    - "share/man/man1/distrobox-stop.1"
    - "share/man/man1/distrobox-upgrade.1"
- name: Distrobox | Installer
  ansible.builtin.shell: '{{ dotfyls_role_files }}/install'
  when: stat_result.skipped or (stat_result.failed is defined and stat_result.failed)
