---
- name: Distrobox | Install dependencies
  ansible.builtin.dnf:
    name: '{{ item }}'
  become: true
  loop:
    - podman
- name: Distrobox | Install
  ansible.builtin.dnf:
    name: distrobox
  become: true
