---
- name: QOL | Install
  ansible.builtin.dnf:
    name: '{{ item }}'
  become: true
  loop:
    - bat
    - thefuck
    - tldr
  # 0.9.4 resolves issues with completion
- name: QOL - Zoxide | Install (Distrobox Alpine Edge)
  ansible.builtin.shell:
    cmd: distrobox-assemble create
    chdir: '{{ dotfyls_role_files }}/zoxide'
  register: result
  changed_when: "'exported successfully' in result.stdout"
  failed_when: "result.rc != 0 and 'fastfetch already exists' not in result.stderr"
