---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: QOL - thefuck | Config link
  ansible.builtin.file:
    src: '{{ dotfyls_role_files }}/thefuck'
    path: '{{ dotfyls_xdg_config_home }}/thefuck'
    state: link
    mode: '0755'
