---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Zsh | Config directory
  ansible.builtin.file:
    path: '{{ dotfyls_xdg_config_home }}/zsh'
    state: directory
    mode: '0755'
- name: Zsh | Config link
  ansible.builtin.file:
    src: '{{ dotfyls_role_files }}/{{ item.name }}'
    path: '{{ dotfyls_xdg_config_home }}/zsh/{{ item.become }}'
    state: link
    mode: '0644'
  loop:
    - { name: zshenv, become: .zshenv }
    - { name: zshrc, become: .zshrc }
  loop_control:
    label: '{{ item.name }}'
- name: Zsh | Default
  ansible.builtin.shell: chsh -s "$(which zsh)" "${SUDO_USER}"
  become: true
  register: result
  changed_when: "'not changed' not in result.stderr"
