---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Zsh | Config directory
  ansible.builtin.file:
    path: '{{ dotfyls_xdg_config_home }}/zsh'
    state: directory
    mode: '0755'
- name: Zsh | Config link (.zshenv)
  ansible.builtin.file:
    src: '{{ dotfyls_role_files }}/.zshenv'
    path: '{{ dotfyls_xdg_config_home }}/zsh/.zshenv'
    state: link
    mode: '0644'
- name: Zsh | Config link (.zshrc)
  ansible.builtin.file:
    src: '{{ dotfyls_role_files }}/.zshrc'
    path: '{{ dotfyls_xdg_config_home }}/zsh/.zshrc'
    state: link
    mode: '0644'
- name: Zsh | Default
  ansible.builtin.shell: 'chsh -s "$(which zsh)" "${SUDO_USER}"'
  become: true
  register: result
  changed_when: "'not changed' not in result.stderr"
