---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Zsh | Config pull
  ansible.builtin.git:
    repo: git@gitlab.com:dotfyls/zsh.git
    dest: "{{ ansible_env['ZDOTDIR'] }}"
- name: Zsh | Configure default
  ansible.builtin.shell: chsh -s "$(which zsh)" "${SUDO_USER}"
  become: true
  register: result
  changed_when: "'not changed' not in result.stderr"
