---
- ansible.builtin.import_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Wezterm | Config pull
  ansible.builtin.git:
    repo: git@gitlab.com:dotfyls/wezterm.git
    dest: '{{ dotfyls_xdg_config_home }}/wezterm'
