_:

{
  imports = [
    ./bat.nix
    ./brightnessctl.nix
    ./cbonsai.nix
    ./cliphist.nix
    ./discord.nix
    ./dunst.nix
    ./eza.nix
    ./fastfetch
    ./fd.nix
    ./firefox.nix
    ./fzf.nix
    ./git.nix
    ./gnome-keyring.nix
    ./gvfs.nix
    ./libreoffice.nix
    ./mpv.nix
    ./nemo.nix
    ./neovim.nix
    ./network-manager-applet.nix
    ./nix-index.nix
    ./obsidian.nix
    ./openrgb.nix
    ./pix.nix
    ./prismlauncher.nix
    ./ripgrep.nix
    ./rofi.nix
    ./sl.nix
    ./solaar.nix
    ./spotify.nix
    ./starship.nix
    ./steam.nix
    ./swww.nix
    ./thefuck
    ./tldr.nix
    ./ventoy.nix
    ./vesktop
    ./waybar.nix
    ./wl-clipboard.nix
    ./xwaylandvideobridge.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
