---
- name: Create Environment | Config directory
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/environment.d'
    state: directory
    mode: '0755'
- name: Create Environment | Config link
  ansible.builtin.file:
    src: '{{ role_path }}/files/{{ item.name }}.conf'
    path: '{{ ansible_user_dir }}/.config/environment.d/{{ item.name }}.conf'
    state: link
    mode: '0644'
  when: item.tag not in ansible_skip_tags and (item.tag in ansible_run_tags or 'all' in ansible_run_tags or item.tag == 'always')
  loop:
    - { name: 10-editor-neovim, tag: neovim }
    - { name: 10-xdg, tag: always }
    - { name: 11-xdg-develop_go, tag: develop_go }
    - { name: 11-xdg-develop_javascript, tag: develop_javascript }
    - { name: 11-xdg-develop_python, tag: develop_python }
    - { name: 11-xdg-develop_rust, tag: develop_rust }
    - { name: 11-xdg-zsh, tag: zsh }
    - { name: 97-path-develop_go, tag: develop_go }
    - { name: 98-path-develop_rust, tag: develop_rust }
    - { name: 99-path, tag: always }
  loop_control:
    label: '{{ item.name }}'
- name: Create Environment | Config compare
  ansible.builtin.script: '{{ role_path }}/files/compare.sh -o {{ role_path }}/files/.applied {{ ansible_user_dir }}/.config/environment.d/*.conf'
  register: result
  changed_when: false
  failed_when: result.stderr != '' or result.rc not in [0, 1]
- name: Create Environment | Prompt restart
  ansible.builtin.debug:
    msg: This machine must be restarted for environment variables to take effect
  when: result.rc != 0
  failed_when: true
