---
- name: Create Environment | Config directory
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/environment.d'
    state: directory
    mode: '0755'
- name: Create Environment | Config link (10-xdg.conf)
  ansible.builtin.file:
    src: '{{ role_path }}/files/10-xdg.conf'
    path: '{{ ansible_user_dir }}/.config/environment.d/10-xdg.conf'
    state: link
    mode: '0644'
- name: Create Environment | Config link (11-develop_rust.conf)
  ansible.builtin.file:
    src: '{{ role_path }}/files/11-develop_rust.conf'
    path: '{{ ansible_user_dir }}/.config/environment.d/11-develop_rust.conf'
    state: link
    mode: '0644'
  when: "'develop_rust' not in ansible_skip_tags and ('develop_rust' in ansible_run_tags or 'all' in ansible_run_tags)"
- name: Create Environment | Config link (11-zsh.conf)
  ansible.builtin.file:
    src: '{{ role_path }}/files/11-zsh.conf'
    path: '{{ ansible_user_dir }}/.config/environment.d/11-zsh.conf'
    state: link
    mode: '0644'
  when: "'zsh' not in ansible_skip_tags and ('zsh' in ansible_run_tags or 'all' in ansible_run_tags)"
- name: Create Environment | Config compare
  ansible.builtin.script: '{{ role_path }}/files/compare.sh {{ ansible_user_dir }}/.config/environment.d/*.conf'
  register: result
  changed_when: false
  failed_when: 'result.stderr != "" or result.rc not in [0, 1]'
- name: Create Environment | Prompt restart
  ansible.builtin.debug:
    msg: This machine must be restarted for environment variables to take effect
  when: result.rc != 0
  failed_when: true
